export * from './account.service';
import { AccountService } from './account.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './data.service';
import { DataService } from './data.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './expense.service';
import { ExpenseService } from './expense.service';
export * from './integration.service';
import { IntegrationService } from './integration.service';
export * from './travel.service';
import { TravelService } from './travel.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './values.service';
import { ValuesService } from './values.service';
export const APIS = [AccountService, DashboardService, DataService, DocumentService, ExpenseService, IntegrationService, TravelService, UserService, ValuesService];
