/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentTyp { 
    DocumentId?: number;
    ReferenceType?: number;
    ModuleId?: number;
    RequestId?: number;
    ReferenceId?: number;
    FileName?: string;
    Guid?: string;
    Location?: string;
    Remarks?: string;
    Password?: string;
    TransactionReference?: string;
}

