/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRequestCostCentrewiseAmmoutType { 
    ExpenseRequestCostCentrewiseAmmoutId?: number;
    ExpenseRequestDetailId?: number;
    CostCentreId?: number;
    CostCentre?: string;
    AmmoutInPercentage?: number;
    AmmoutInActual?: number;
    TransactionReference?: string;
}

