/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRequestDetailMetaDataType { 
    ExpenseRequestMetaDataId?: number;
    ExpenseRequestMetaId?: number;
    ExpenseRequestDetailId?: number;
    IntegerValue?: number;
    NumericValue?: number;
    DatetimeValue?: string;
    VarcharValue?: string;
    BitValue?: boolean;
    UniqueIdentifierValue?: string;
    RelatedToId?: number;
    TransactionReference?: string;
}

