/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRequestCostCentrewiseAmountRemoveParam { 
    Id?: number;
    ExpenseRequestDetailId?: number;
    Status?: string;
    IsEdit?: boolean;
    IsView?: boolean;
    IsViewLog?: boolean;
    IsRemove?: boolean;
    IsMakeActive?: boolean;
    IsMapping?: boolean;
    TransactionId?: string;
    CreatedById?: number;
    CreatedBy?: string;
    ModifiedById?: number;
    ModifiedBy?: string;
    CreatedDate?: string;
    readonly CreatedDateString?: string;
    ModifiedDate?: string;
    readonly ModifiedDateString?: string;
    IsActive?: boolean;
    ActionBy?: number;
    CommunicationSeenCount?: number;
}

