/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseRequestMetaDataType } from './expenseRequestMetaDataType';
import { ConstraintType } from './constraintType';


export interface ExpensePolicyEntitlementBoardingParam { 
    ClaimTypeId?: number;
    TravelRequestId?: number;
    UserMasterId?: number;
    ExpenseCategoryId?: number;
    ReferenceFromDate?: string;
    ReferenceToDate?: string;
    CityGradeId?: number;
    CountryGradeId?: number;
    ExpenseRequestMetaDataType?: Array<ExpenseRequestMetaDataType>;
    ConstraintType?: Array<ConstraintType>;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

