/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseRequestGstInsertParam { 
    ExpenseRequestGstId?: number;
    ExpenseRequestDetailId?: number;
    GstIn?: string;
    VendorName?: string;
    InvoiceNumber?: string;
    Amount?: number;
    Basic?: number;
    CGST?: number;
    SGST?: number;
    IGST?: number;
    UGST?: number;
    CESS?: number;
    Gross?: number;
    HSN_SAC_Code?: string;
    StateCode?: string;
    TaxCode?: string;
    CostcenterId?: number;
    TransactionReference?: string;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

