/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseRequestDetailType } from './expenseRequestDetailType';
import { RelocationExpenseOtherVendorQuoteDetailsType } from './relocationExpenseOtherVendorQuoteDetailsType';
import { ExpenseRequestMetaDataType } from './expenseRequestMetaDataType';
import { ExpenseRequestCostCentrewiseAmmoutType } from './expenseRequestCostCentrewiseAmmoutType';
import { ExpenseRequestGstType } from './expenseRequestGstType';
import { DocumentTyp } from './documentTyp';
import { ExpenseRequestDetailMetaDataType } from './expenseRequestDetailMetaDataType';


export interface ExpenseRequestModel { 
    ExpenseRequestId?: number;
    RequestForId?: number;
    ClaimTypeId?: number;
    RequesterId?: number;
    TravelRequestId?: number;
    RequestDate?: string;
    Purpose?: string;
    CostCentreId?: number;
    BillableCostCentreId?: number;
    Remarks?: string;
    IsDraft?: boolean;
    ExpenseRequestDetailType?: Array<ExpenseRequestDetailType>;
    ExpenseRequestMetaDataType?: Array<ExpenseRequestMetaDataType>;
    ExpenseRequestDetailMetaDataType?: Array<ExpenseRequestDetailMetaDataType>;
    ExpenseRequestGstType?: Array<ExpenseRequestGstType>;
    ExpenseRequestCostCentrewiseAmmoutType?: Array<ExpenseRequestCostCentrewiseAmmoutType>;
    RelocationExpenseOtherVendorQuoteDetailsType?: Array<RelocationExpenseOtherVendorQuoteDetailsType>;
    DocumentType?: Array<DocumentTyp>;
    ActionBy?: number;
    ExpenseCategoryGroupId?: number;
}

