/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpenseCategoryGroupMapping { 
    Id?: number;
    CategoryGroupId?: number;
    ExpenseCategoryId?: number;
    CreatedDate?: string;
    ModifiedDate?: string;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

