/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelRequestVisitorType } from './travelRequestVisitorType';
import { TravelRequestGroupType } from './travelRequestGroupType';


export interface GuestHouseListParam { 
    UserMasterId?: number;
    CityId?: number;
    RequestForId?: number;
    CheckInDate?: string;
    CheckOutDate?: string;
    TravelRequestGroupType?: Array<TravelRequestGroupType>;
    TravelRequestVisitorType?: Array<TravelRequestVisitorType>;
}

