/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginViewModel { 
    EmployeeCode: string;
    Password: string;
    LogInTypeId?: number;
    IpAddress?: string;
    Browser?: string;
    UserTypeId?: number;
    AppVersion?: string;
    IMEI?: string;
    AppBaseUrl?: string;
    ClientCode?: string;
}

