/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RelocationExpenseOtherVendorQuoteDetailsType { 
    RelocationExpenseOtherVendorQuoteDetailsTypeId?: number;
    ExpenseRequestDetailId?: number;
    VendorName?: string;
    QuoteNumber?: string;
    QuoteDate?: string;
    Amount?: number;
    TransactionId?: string;
    TransactionReference?: string;
}

