/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchYatraParam { 
    ArrivalCityCode?: string;
    DepartureCityCode?: string;
    AdultCount?: number;
    ChildCount?: number;
    InfantCount?: number;
    Class?: string;
    FlightDepartDate?: string;
    ArrivalCountryCode?: string;
    DepartureCountryCode?: string;
    ReferenceEmployeeId?: number;
}

