/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TicketOptionsYatraParam { 
    TripId?: string;
    SearchQueryId?: string;
    DepartureDatetime?: string;
    readonly DepartureDateTimeString?: string;
    ArrivalDateTime?: string;
    readonly ArrivalDateTimeString?: string;
    IsNonStop?: boolean;
    TransactionId?: string;
    IsVerticalDesign?: boolean;
}

