/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestAdvanceType { 
    TravelRequestAdvanceTypeId?: number;
    CurrencyAsPerPolicy?: number;
    AmountAsPerPolicy?: number;
    Currency?: number;
    Amount?: number;
    DisbursementMode?: number;
    CollectionOn?: string;
    Remarks?: string;
}

