/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestVisitorType { 
    TravelRequestVisitorId?: number;
    FisrtName?: string;
    LastName?: string;
    AgeGroup?: number;
    Age?: number;
    Gender?: number;
    Nationality?: string;
    MobileNumber?: string;
    Organization?: string;
    IdentityReferenceId?: number;
    IdentityReference?: string;
    Remarks?: string;
    TransactionId?: string;
}

