/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestTicketOptionApiType { 
    TripId?: string;
    FlightIdentifier?: string;
    IsSelected?: boolean;
    Remarks?: string;
    TransactionReference?: string;
}

