/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestAccommodationType { 
    TravelRequestAccommodationId?: number;
    StayType?: number;
    StayReferenceId?: number;
    Location?: number;
    CheckIn?: string;
    CheckOut?: string;
    NumberOfNight?: number;
    NumberOfRoom?: number;
    SpecialInstruction?: string;
    ServiceAgentReferenceId?: number;
}

