/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelRequestTicketOptionApiType } from './travelRequestTicketOptionApiType';
import { TravelRequestAccommodationType } from './travelRequestAccommodationType';
import { TravelRequestCabType } from './travelRequestCabType';
import { TravelRequestMetaDataType } from './travelRequestMetaDataType';
import { TravelRequestTicketType } from './travelRequestTicketType';
import { TravelRequestAdvanceCountryWiseType } from './travelRequestAdvanceCountryWiseType';
import { Document } from './document';
import { TravelRequestServiceMappingType } from './travelRequestServiceMappingType';
import { TravelRequestLeaveInsertParam } from './travelRequestLeaveInsertParam';
import { TravelRequestVisitorType } from './travelRequestVisitorType';
import { TravelRequestAdvanceType } from './travelRequestAdvanceType';
import { TravelRequestGroupType } from './travelRequestGroupType';


export interface TravelRequestInsertParam { 
    TravelRequestId?: number;
    TravelTypeId?: number;
    TravelRequestForId?: number;
    TravelDateFrom?: string;
    TravelDateTo?: string;
    EmployeeId?: number;
    ReferenceEmployeeId?: number;
    IsDraft?: boolean;
    IsPostFacto?: boolean;
    IsTravelDateRestriction?: boolean;
    TravelRequestMetaDataType?: Array<TravelRequestMetaDataType>;
    TravelRequestGroupType?: Array<TravelRequestGroupType>;
    TravelRequestVisitorType?: Array<TravelRequestVisitorType>;
    TravelRequestServiceMappingType?: Array<TravelRequestServiceMappingType>;
    TravelRequestTicketType?: Array<TravelRequestTicketType>;
    TravelRequestAccommodationType?: Array<TravelRequestAccommodationType>;
    TravelRequestCabType?: Array<TravelRequestCabType>;
    TravelRequestAdvanceType?: Array<TravelRequestAdvanceType>;
    TravelRequestAdvanceCountryWiseType?: Array<TravelRequestAdvanceCountryWiseType>;
    TravelRequestTicketOptionApiType?: Array<TravelRequestTicketOptionApiType>;
    TravelRequestLeaveType?: Array<TravelRequestLeaveInsertParam>;
    Documents?: Array<Document>;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

