/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestTicketType { 
    TravelRequestTicketId?: number;
    Origin?: number;
    Destination?: number;
    DepartureDatetime?: string;
    ArrivalDatetime?: string;
    TravelMode?: number;
    TravelClass?: number;
    TicketSearchConstraintId?: number;
    Remarks?: string;
    IsViolation?: boolean;
    IsOCRRestrictedKeyword?: boolean;
    TransactionId?: string;
    IsAPI?: boolean;
    IsSelfBookedTicket?: boolean;
}

