/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelRequestMetaDataType } from './travelRequestMetaDataType';


export interface TravelRequestBudgetSegregationInsertParam { 
    TravelRequestId?: number;
    ApprovalAction?: number;
    TravelRequestMetaDataType?: Array<TravelRequestMetaDataType>;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

