/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestCabType { 
    TravelRequestCabId?: number;
    PickupLocation?: number;
    PickupAddress?: string;
    PickupDatetime?: string;
    DestinationLocation?: number;
    DestinationAddress?: string;
    ReturnDatetime?: string;
    PaxCount?: number;
    CarType?: number;
    CabTripType?: number;
    ServiceAgentReferenceId?: number;
    Remarks?: string;
}

