/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestDateExtensionParam { 
    TravelRequestId?: number;
    TravelDateFrom?: string;
    TravelDateTo?: string;
    Remarks?: string;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

