/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelCancellationServiceType } from './travelCancellationServiceType';


export interface TravelRequestCancellationParam { 
    TravelRequestId?: number;
    Remarks?: string;
    IsCancelCompleteRequest?: boolean;
    TravelCancellationServiceType?: Array<TravelCancellationServiceType>;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

