/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TravelRequestLeaveInsertParam { 
    TravelRequesLeaveId?: number;
    TravelRequestId?: number;
    LeaveFromDate?: string;
    LeaveToDate?: string;
    LeaveRemarks?: string;
    Status?: string;
    TransactionId?: string;
}

