/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserMasterMetaDataType } from './userMasterMetaDataType';


export interface UserMasterMetaDataInsertParam { 
    UserMasterId?: number;
    UserMasterMetaDataType?: Array<UserMasterMetaDataType>;
    IsActive?: boolean;
    Status?: string;
    ActionBy?: number;
    TransactionId?: string;
    CommunicationSeenCount?: number;
}

