/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelRequestGroupType } from './travelRequestGroupType';


export interface ValidateTravelTicketPolicyParam { 
    UserMasterId?: number;
    TravelTypeId?: number;
    TravelModeId?: number;
    TravelClassId?: number;
    RequestForId?: number;
    FromCityId?: number;
    ToCityId?: number;
    ReferenceDate?: string;
    TravelRequestGroupType?: Array<TravelRequestGroupType>;
}

