/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateExpenseClaimLocalTravelConveyanceParam { 
    UserMasterId?: number;
    IsKmLimitRequired?: boolean;
    DistanceLimitPerDay?: number;
    Distance?: number;
    LocalTravelMode?: number;
    ClaimedDate?: string;
    TravelRequestId?: number;
}

