/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateGuestHouseEligibilityParam { 
    UserMasterId?: number;
    TravelTypeId?: number;
    RequestForId?: number;
    CityId?: number;
    CheckInDate?: string;
    CheckOutDate?: string;
}

