/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateBillingParam { 
    ExpenseCategoryId?: number;
    UserMasterId?: number;
    BillingFromDate?: string;
    BillingToDate?: string;
    BillNumber?: string;
    BillDate?: string;
    Vendor?: string;
    Amount?: string;
}

