/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TravelRequestAdvanceCountryWiseType } from './travelRequestAdvanceCountryWiseType';
import { TravelRequestAdvanceType } from './travelRequestAdvanceType';


export interface ValidateTravelAdvancePolicyParam { 
    UserMasterId?: number;
    TravelTypeId?: number;
    RequestForId?: number;
    TravelStartDate?: string;
    TravelEndDate?: string;
    TravelRequestAdvanceType?: Array<TravelRequestAdvanceType>;
    TravelRequestAdvanceCountryWiseType?: Array<TravelRequestAdvanceCountryWiseType>;
}

